---
# update: true
# swapfile_path: /swapfile
# swapfile_size: 8G

source_key: "./.ssh/id_rsa"
dest_key: "{{ homedir }}/.ssh/id_rsa"

homedir: "{{ lookup('env','HOME') }}"
srcdir: "{{ homedir }}/.src"

base_packages:
  - base
  - base-devel
  - linux
  - linux-firmware
  - sudo
  - curl
  - dhcpcd
  - netctl
  - networkmanager
  - openssh
  - pipewire
  - man-db
  - man-pages
  - git
  - wget
  - reflector
  - neovim

gpu_packages:
  - nvidia-dkms
  - nvidia-utils
  - egl-wayland

hyprland_packages:
  - hyprcursor
  - hypridle
  - hyprland
  # - hyprlang
  - hyprlock
  - hyprpaper
  - hyprutils-git
  - hyprwayland-scanner
  - xdg-desktop-portal-hyprland
  - dunst
  - pipewire
  - wireplumber
  - hyprpolkitagent
  - qt5-wayland
  - qt6-wayland

font_packages:
  # - ttf-ubuntu-font-family
  # - noto-fonts
  # - noto-fonts-emoji # for emoji
  # - ttf-dejavu
  # - ttf-roboto
  # - adobe-source-han-sans-otc-fonts # for CJK
    - ttf-jetbrains-mono-nerd

other_packages:
  # - bash-completion
  # - mpv
  # - mpv-mpris
  # - aria2
  - yay
  # - pass
  - stow
  - firefox
  - chromium
  # - google-chrome
  - obsidian
  - spotify
  # - spotify-adblock-git
  - alacritty
  # - yt-dlp
  # - ntfs-3g
  # - gallery-dl
  # - neofetch
  - btop
  # - geary
  # - browserpass-firefox
  # - browserpass-chromium
  - tmux
  # - cpupower
  # - turbostat
  # - acpi
  # - bc
  # - update-grub
  # - p7zip
  # - radeontop
  # - xclip
  - dunst
  - rofi
  - sddm
  - bluez

services_list:
  - sshd
  - NetworkManager
  - reflector
  - bluetooth
  - sddm
  - reflector.timer
  - fstrim.timer


dev_packages:
  # - vscodium-bin
  - rustup
  - pyenv
  - ripgrep
  - zoxide
  - bat
