- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Run the equivalent of "pacman -Syu" as a separate step
    community.general.pacman:
      update_cache: true
      upgrade: true
      tags:
        - install
        - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/basic-setup.yml

