- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Run the equivalent of "pacman -Syu" as a separate step
    community.general.pacman:
      update_cache: true
      upgrade: true
    tags:
      - install
      - core
  tasks:
    - name: ssh config
      ansible.builtin.import_tasks:
        file: tasks/ssh.yml
    - name: git setup
      ansible.builtin.import_tasks:
        file: tasks/git-setup.yml
    - name: dotfiles
      ansible.builtin.import_tasks:
         file: tasks/dotfiles.yml
    - name: Basic setup
      ansible.builtin.import_tasks:
        file: tasks/basic-setup.yaml
    - name: Basic setup
      ansible.builtin.import_tasks:
          file: tasks/zsh-setup.yml
