---
- name: Install gpu packages
  # become: true
  kewlfft.aur.aur:
    name: "{{ gpu_packages }}"
    use: yay
    state: present
  changed_when: false

- name: setup nvida
  become: yes
  ansible.builtin.file:
    src: "{{ homedir }}/ansible/dotfiles/.extra/nvidia/nvidia.conf"
    path: /etc/modprobe.d/nvidia.conf
    state: link
