---
- name: Install hyprland packages
  # become: true
  kewlfft.aur.aur:
    name: "{{ hyprland_packages }}"
    use: yay
    state: present

- name: build headers
  shell: hyprpm update

- name: Install hy3
  shell: hyprpm add https://github.com/outfoxxed/hy3

- name: update plugins
  shell: hyprpm update

- name: enable hy3
  shell: hprpm enable hy3
