---
- name: Remove mkinitcpio
  become: yes
  ansible.builtin.file:
    path: /etc/mkinitcpio.conf
    state: absent

- name: sym link mkinitcpio.conf
  become: yes
  ansible.builtin.file:
    src: "{{ homedir }}/ansible/dotfiles/.extra/mkinitcpio/mkinitcpio.conf"
    dest: /etc/mkinitcpio.conf
    state: link

- name: Install mkinitcpio packages
  # become: true
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    state: present
  changed_when: false
  loop:
    - mkinitcpio-bluetooth
    - mkinitcpio-numlock

- name: rebuild mkinitcpio
  become: yes
  shell: mkinitcpio -p linux
