---
- name: Install other packages
  # become: true
  kewlfft.aur.aur:
    name: shim-signed
    use: yay
    state: present

- name: stat boot
  stat: path=/boot/EFI/BOOT/BOOTX64.EFI
  register: boot_stat

- name: Rename bootloader
  become: yes
  command: sudo mv /boot/EFI/BOOT/BOOTX64.EFI /boot/EFI/BOOT/grubx64.efi
  when: boot_stat.stat.exists

- name: Copy shim boot loader
  become: yes
  command: cp /usr/share/shim-signed/shimx64.efi /boot/EFI/BOOT/BOOTX64.EFI

- name: copy other shim stuff
  become: yes
  command: cp /usr/share/shim-signed/mmx64.efi /boot/EFI/BOOT/

- name: setup nvram
  become: yes
  command: efibootmgr --unicode --disk /dev/sda --part 1 --create --label "Shim" --loader /EFI/BOOT/BOOTX64.EFI

